version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    networks:
      - app-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - app-network

  resume-analyzer:
    build:
      context: ./resume-analyzer
    container_name: resume-analyzer
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - app-network

  resume-generator:
    build:
      context: ./resume-generator
    container_name: resume-generator
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test_db
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge