services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_DATABASE: ResumeGenerator
    ports:
      - "27017:27017"  # MongoDB будет доступен на порту 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
  redis:
    image: redis:7.4.2
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass root
    volumes:
      - ./data:/data
  app:
    build: .
    container_name: spring-boot-app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ResumeGenerator  # Используем имя контейнера mongodb для подключения
    ports:
      - "8082:8082"  # Приложение будет доступно на порту 8082
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge